version: 1.0

environments:
    coder:
        files:
            - name: "project files"
              include:

                  - "./libs/*/*.(json|yml|ts|scss)"
                  - "./libs/*/**.(js|html|css|ts|scss)"

              instructions: |
                  These are all project files. You can edit them as you like.
