name: Publish

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

on:
  push:
    tags:
      - 'nxa**'

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@nextrap'

      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx report
      - name: Extract tagged package
        id: package_name
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: return context.payload.ref.replace(/\/refs\/tags\//, '').replace(/@.*/, '');
      - run: npx nx run -p "${steps.package_name.outputs.result}" -t test build
      - run: npx nx release publish --access public -p "${steps.package_name.outputs.result}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
