name: Publish Latest

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@nextrap'

      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - run: npx nx report
      - run: npx nx run-many -t lint test build
      - run: npx nx release publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
